version: 2.1

orbs:
  ci-caching: serbiatech/ci-caching@0.0.4

jobs:

  # Install dependencies job

  install-dependencies-with-docker:
    machine: true
    parameters:
      dependencyCheckSumFile:
        type: string
        default: "./composer.lock"
      dependencyCachePath:
        type: string
        default: "./vendor"
      dependencyAdditionalCacheKey:
        type: string
        default: "v1"
      sshKeyFilename:
        type: string
        default: "docker_rsa"
      sshFingerprint:
        type: string
        default: ""
      dockerImageTag:
        type: string
        default: "ci-composer"
      dockerFolder:
        type: string
        default: "./docker/composer"
      dockerAdditionalCacheKey:
        type: string
        default: "v1"
      localMountPath:
        type: string
        default: "${PWD}"
      dockerVolumePath:
        type: string
        default: "/var/www/html"
      installCommand:
        type: string
        default: "install"
    steps:
      - install-dependencies-with-docker-command:
          dependencyCheckSumFile: << parameters.dependencyCheckSumFile >>
          dependencyCachePath: << parameters.dependencyCachePath >>
          dependencyAdditionalCacheKey: << parameters.dependencyAdditionalCacheKey >>
          sshKeyFilename: << parameters.sshKeyFilename >>
          sshFingerprint: << parameters.sshFingerprint >>
          dockerImageTag: << parameters.dockerImageTag >>
          dockerFolder: << parameters.dockerFolder >>
          dockerAdditionalCacheKey: << parameters.dockerAdditionalCacheKey >>
          dockerVolumePath: << parameters.dockerVolumePath >>
          localMountPath: << parameters.localMountPath >>
          installCommand: << parameters.installCommand >>

  # Run coverage

  coverage:
    machine: true
    parameters:
      coverageDir:
        type: string
        default: "./build/logs/phpunit/coverage"
      testResultDir:
        type: string
        default: "./build/logs/phpunit"
      dockerComposeFile:
        type: string
        default: "./docker/docker-compose.ci.yml"
      dockerCheckSumDir:
        type: string
        default: "./docker"
      dependencyCheckSumFile:
        type: string
        default: "./composer.lock"
#      hostToWaitFor:
#        type: string
#        default: ""
      command:
        type: string
        default: "run coverage"
    steps:
      - coverage-command:
          coverageDir: << parameters.coverageDir >>
          testResultDir: << parameters.testResultDir >>
          dockerComposeFile: << parameters.dockerComposeFile >>
          dockerCheckSumDir: << parameters.dockerCheckSumDir >>
          dependencyCheckSumFile: << parameters.dependencyCheckSumFile >>
#          hostToWaitFor: << parameters.hostToWaitFor >>
          command: << parameters.command >>

commands:

  # Add SSH key command

  add-ssh-key-command:
    parameters:
      sshKeyFilename:
        type: string
        default: "docker_rsa"
      sshFingerprint:
        type: string
        default: ""
    steps:
      - when:
          condition: << parameters.sshFingerprint >>
          steps:
            - add_ssh_keys:
                fingerprints:
                  - << parameters.sshFingerprint >>
            - run:
                name: Copy ssh key
                command: |
                  SSH_FINGERPRINT=<< parameters.sshFingerprint >>
                  cp ~/.ssh/id_rsa_"${SSH_FINGERPRINT//:}" ~/.ssh/<< parameters.sshKeyFilename >>

  # Install dependencies with docker

  install-dependencies-with-docker-command:
    parameters:
      dependencyCheckSumFile:
        type: string
        default: "./composer.lock"
      dependencyCachePath:
        type: string
        default: "./vendor"
      dependencyAdditionalCacheKey:
        type: string
        default: "v1"
      sshKeyFilename:
        type: string
        default: "docker_rsa"
      sshFingerprint:
        type: string
        default: ""
      installCommand:
        type: string
        default: "install"
      dockerImageTag:
        type: string
        default: "ci-composer"
      dockerFolder:
        type: string
        default: "./docker/composer"
      localMountPath:
        type: string
        default: "${PWD}"
      dockerVolumePath:
        type: string
        default: "/var/www/html"
      dockerAdditionalCacheKey:
        type: string
        default: "v1"
    steps:
      - checkout
      - ci-caching/dependency-cache-load:
          checkSumFile: << parameters.dependencyCheckSumFile >>
          additionalCacheKey: << parameters.dependencyAdditionalCacheKey >>
      - ci-caching/dependency-check:
          cacheDataPath: << parameters.dependencyCachePath >>
      - add-ssh-key-command:
          sshKeyFilename: << parameters.sshKeyFilename >>
          sshFingerprint: << parameters.sshFingerprint >>
      - ci-caching/docker-images-cache-load:
          dockerCheckSumDir: << parameters.dockerFolder >>
          additionalCacheKey: << parameters.dockerAdditionalCacheKey >>
          baseCacheName: << parameters.dockerImageTag >>
      - ci-caching/docker-layers-load:
          cacheFile: ~/<< parameters.dockerImageTag >>.tar
      - run:
          name: Install php dependencies
          command: |
            docker run --rm -v ~/.ssh/<< parameters.sshKeyFilename >>:/home/www-data/.ssh/id_rsa:ro -v "<< parameters.localMountPath >>":<< parameters.dockerVolumePath >> << parameters.dockerImageTag >> << parameters.installCommand >>
      - ci-caching/dependency-cache-save:
          checkSumFile: << parameters.dependencyCheckSumFile >>
          cacheDataPath: << parameters.dependencyCachePath >>
          additionalCacheKey: << parameters.dependencyAdditionalCacheKey >>

  # Coverage command

  coverage-command:
    parameters:
      coverageDir:
        type: string
        default: "./build/logs/phpunit/coverage"
      testResultDir:
        type: string
        default: "./build/logs/phpunit"
      dockerComposeFile:
        type: string
        default: "./docker/docker-compose.ci.yml"
      dockerCheckSumDir:
        type: string
        default: "./docker"
      dependencyCheckSumFile:
        type: string
        default: "./composer.lock"
      hostToWaitFor:
        type: string
        default: "composer"
      command:
        type: string
        default: "run coverage"
    steps:
      - ci-caching/run-docker-from-restored-caches:
          dockerCheckSumDir: << parameters.dockerCheckSumDir >>
          dependencyCheckSumFile: << parameters.dependencyCheckSumFile >>
          dockerComposeFile: << parameters.dockerComposeFile >>
#      - wait-for-host-command:
#          host: << parameters.hostToWaitFor >>
      - ci-caching/execute-with-external-container:
          info: Execute tests with code coverage
          container: composer
          dockerComposeFile: << parameters.dockerComposeFile >>
          command: << parameters.command >>
#      - ci-caching/execute-in-container:
#          info: Execute tests with code coverage
#          container: php
#          dockerComposeFile: << parameters.dockerComposeFile >>
#          command: << parameters.command >>
      - store_artifacts:
          path: << parameters.coverageDir >>
      - store_test_results:
          path: << parameters.testResultDir >>

  # Wait for the host command

#  wait-for-host-command:
#    parameters:
#      info:
#        type: string
#        default: "Wait for host"
#      host:
#        type: string
#        default: ""
#      container:
#        type: string
#        default: php
#    steps:
#      - when:
#          condition: << parameters.host >>
#          steps:
#            - install-dockerize-command:
#                container: php
#            - ci-caching/execute-in-container:
#                info: << parameters.info >>
#                container: << parameters.container >>
#                command: dockerize -wait << parameters.host >> -timeout 1m
